### ISSUE TITLE
JWT access token expiration only checked once

### ISSUE THREAD

**Issue by gbotka** [spring-cloud/spring-cloud-security#104]
Once the client is authenticated, it never checks the JWT token expiration again. Thus if we use `org.springframework.cloud.security.oauth2.proxy.OAuth2TokenRelayFilter`, we can send out expired tokens to the resource servers, which cannot refresh it.
I think the correct behaviour should be to check expiration of JWT token, and refresh or reissue it if it is expired.

**Comment by gbotka** [comment]
@dsyer Can you confirm that would be the correct behaviour?

**Comment by dsyer** [comment]
A client isn't necessarily going to be able to do that pre-emptively (the token is opaque), but it can respond to 403s from the resource server and retry. that's what `OAuth2RestTemplate` does.
