### ISSUE TITLE
JWT Token Relay with Hystrix and Ribbon

### ISSUE THREAD

**Issue by visusnet** [spring-cloud/spring-cloud-security#118]
Many examples use an ``OAuth2RestTemplate`` (or ``OAuth2RestOperations``) which is usually defined as follows:
```java
@LoadBalanced
@Bean
public OAuth2RestTemplate loadBalancedOauth2RestTemplate(
        OAuth2ProtectedResourceDetails resource, OAuth2ClientContext context) {
    return new OAuth2RestTemplate(resource, context);
}
```
and used like this:
```java
@LoadBalanced
@Autowired
private OAuth2RestTemplate oAuth2RestTemplate;

private User getCurrentUser() {
    return oAuth2RestTemplate.getForObject("http://user-service/v1/me", User.class);
}
```

This should work including token relay, however, JWT, Hystrix and Ribbon make it a little bit more complicated. Ribbon is used for client-side load balancing and Hystrix is used for failover. Both apply some proxying magic which requires some additional pixie dust to get OAuth2 stuff into the thread (https://github.com/spring-cloud/spring-cloud-security/issues/93#issuecomment-245235040). JWT token relay is implemented using a MVC interceptor (https://github.com/spring-cloud/spring-cloud-security/issues/85#issuecomment-245574096) which should redirect the ``Authorization`` header.

I have provided an example project with two similar services (``working-service`` which is using a workaround and ``broken-service`` which uses the usual way described above; both projects don't differ in any other aspect) that use a ``user-service`` for authentication (for simplicity, it will accept every user, if necessary by creating a new one). All services are behind a Zuul-backed ``edge-service`` and service discovery is implemented using Eureka.

Example: https://github.com/visusnet/broken-oauth2-example

I am assuming that ``broken-service`` should work. But it doesn't. Instead I get this error message:
```
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
```

You can bootstrap the whole project using docker and docker-compose (just run ``bin/run.sh``). Once everything is up, you can run ``bin/oauth.sh`` to simulate the login (=access token retrieval) and further requests to both, the ``working-service`` and the ``broken-service``.

Is this an issue with the project or does the mix of JWT, Hystrix and Ribbon break it?

**Comment by szantopeter** [comment]
See if my https://github.com/spring-cloud/spring-cloud-security/issues/85#issuecomment-297006151 helps

**Comment by dsyer** [comment]
JWT has nothing to do with anything as far as I can tell. Hystrix uses a background thread by default, so I expect that is what causes the request context to be lost. You can switch to semaphore isolation in Hystrix to verify that.

**Comment by visusnet** [comment]
@szantopeter It works. Thank you. Hystrix was not the culprit.
