### ISSUE TITLE
Build SSO cluster with security & oauth2

### ISSUE THREAD

**Issue by TonyLiu0112** [spring-cloud/spring-cloud-security#121]
> I am more shy of my English, a lot of forgiveness :)

Hi, I had to build the cluster of sso,  I use @EnableAuthorizationServer to enable a authentication server, it may be has many instances. I have a gateway server, It performs authentication through multiple authentication instances, I configured like this:

    server:
      port : 8080
    security:
      basic:
        enabled: false
      oauth2:
        client:
          client-id: mud
          client-secret: mud
          access-token-uri: http://localhost:${server.port}/proxy/oauth/token
          user-authorization-uri: http://localhost:${server.port}/proxy/oauth/authorize
          scope: read, write
        resource:
          token-info-uri: http://localhost:${server.port}/proxy/oauth/check_token
      ignored: /proxy/oauth/token, /proxy/oauth/authorize, /proxy/oauth/check_token
    zuul:
      routes:
        auth-server:
          path: /proxy/**
          serviceId: mud-microservice-security
    mud-microservice-security:
      ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    logging:
      level.org.springframework.security: debug

I think it should work like that when I request gateway resources: http://localhost:8080/env, it redirect to http://mud-microservice-security/proxy/oauth/authorize, and then redirect to http://mud-microservice-security/oauth/authorize by zuul, sso server response a login page to user. when success to login by user, finally to redirect to http://localhost:8080/env, but it redirect to http://mud-microservice-security/. I tried do auth without zuul, it works. 

I use zuul because I need to reverse proxy to a number of different authentication servers. Is this the usage of me wrong or is there any better way to do it?

**Comment by dsyer** [comment]
I can't quite figure it all out from just a single config file. Maybe you could share a minimal sample that shows what you are trying to do?

**Comment by gmywq392** [comment]
@TonyLiu0112 Hi,How there going? I'm also struggling in that. Does the Oauth2 cluster works fine now?
