### ISSUE TITLE
Token relay request interceptor is not registered

### ISSUE THREAD

**Issue by szantopeter** [spring-cloud/spring-cloud-security#123]
ResourceServerTokenRelayAutoConfiguration creates a @Bean of HandlerInterceptor (tokenRelayRequestInterceptor) but it is never registered into the Spring MVC InterceptorRegistry, therefore never runs. I believe this approach would work with a Zuul filter but MVC filters have to be explicitly registered. Without this filter token Relay of JWT tokens does not work

**Comment by szantopeter** [comment]
PR is here : https://github.com/spring-cloud/spring-cloud-security/pull/124

**Comment by szantopeter** [comment]
Hi @dsyer have had a chance to look into this bug and pull request https://github.com/spring-cloud/spring-cloud-security/pull/124 that I created to fix it?

**Comment by dsyer** [comment]
OK the PR is merged now. The docs don't need to change, right?

**Comment by szantopeter** [comment]
Hi, I think there is no need for document update!
