### ISSUE TITLE
the problem Zuul with oauth

### ISSUE THREAD

**Issue by fzhsh-q** [spring-cloud/spring-cloud-security#133]
i configure the zuul with `@EnableOAuth2Sso`.
and the ENV:
1. zuul service
2. A service
3. B service

now, the call chain is follow:
Browser -> Zuul -> A Service -> Zuul -> B Service

but, the last request Zuul forwad to B Service is unauthentication, so the call is failed.

does anyone know how to fix it!

**Comment by power-man** [comment]
Do you config  zuul.sensitiveHeaders: Cookie,Set-Cookie,Authorization

**Comment by fzhsh-q** [comment]
thanks a lot. i had fix it, i found the second request had been reset the context.
