### ISSUE TITLE
Upgrade to spring security 5.0.x

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-security#136]

**Comment by thekalinga** [comment]
Appreciate any update on this front.

Looks like the spring security oauth2 client (5.0+) does not like `spring-cloud-starter-oauth2`, as later expects spring mvc to be present on the classpath

Cloud gateway uses webflux & spring webflux does not work well with spring mvc.

Any idea on when the support for cloud gateway can be expected with this?

+ @dsyer

**Comment by dsyer** [comment]
See #141

**Comment by spencergibb** [comment]
Closing as #141 is fixed.
