### ISSUE TITLE
@ResourceServer does not work with JWT on spring-boot 1.5.6

### ISSUE THREAD

**Issue by Ziemowit** [spring-cloud/spring-cloud-security#138]
We use **Dalston.SR4**.

When we try to upgrade from spring-boot **1.5.4** to **1.5.9** (which is advised on main site) our **@ResourceServer** is unable to process JWT access token.

Returned error message is:

```
{"error": "invalid_token","error_description": "Cannot convert access token to JSON"}
```

On 1.5.4 all works correct.
If you need we are able to attach you a code example.

Updated:
------------------------
Ok I have found out more:

Because of some reason for JWT with header:

```
{
  "alg": "RS256",
  "typ": "JWT"
}

```
**MacSigner: HMACSHA256** is chosen in new versions (spring-boot = 1.5.6+, cloud = Edgeware.RELEASE).

Previously it was:

**SHA256withRSA** (spring-boot = 1.5.4, cloud = Dalston.SR4)

So seems that incorrect verifier is used in new version.

**Comment by Ziemowit** [comment]
After discussion on **gitter**.
It was incorrect configuration which was working on previous versions of spring-boot.

After removing below 2 **@Bean**s all works.

```
  @Bean
  public TokenStore tokenStore() {
    return new JwtTokenStore(jwtAccessTokenConverter());
  }

  @Bean
  protected JwtAccessTokenConverter jwtAccessTokenConverter() {
    return new JwtAccessTokenConverter();
  }
```

**Comment by malinovskiy-alex** [comment]
Actually I received the same issue with spring boot 2.x version. I don't have such beans in my config classes so what was the actual problem?
