### ISSUE TITLE
OAuth2TokenRelayFilter not working with KeyCloak as Auth-Server

### ISSUE THREAD

**Issue by rowe42** [spring-cloud/spring-cloud-security#140]
We are using a KeyCloak (http://www.keycloak.org/) as our Auth Server in a Microservice Architecture. Our Frontend is served from a Zuul Gateway, which also uses @EnableOAuth2Sso.

Now, we are getting JWT Access-Tokens from KeyCloak, which Zuul does correctly hand down to the underlying Microservices.

When the Access-Token needs refreshing, this would be done in the `OAuth2TokenRelayFilter` from @dsyer in method `getAccessToken`.

However, in this method we find the line

```
if (restTemplate.getResource().getClientId()
					.equals(auth.getOAuth2Request().getClientId())) {
```

which does never evaluate to true in our case.
The reason is that `auth.getOAuth2Request().getClientId()` is `null`. Through debugging we found out that the clientId is set in class `DefaultAccessTokenConverter` in method `extractAuthentication`.

There we find the line

```
String clientId = (String) map.get(CLIENT_ID);
```

where

```
final String CLIENT_ID = "client_id";
```

But, in the JWT tokens from KeyCloak there is no such claim "client_id" and can also not be set. 
(I must admit there is a Client ID mapper, but somehow this doesn't fill in a claim:
![image](https://user-images.githubusercontent.com/25983841/36539502-5e9788da-17d7-11e8-8a76-ac35df7f0210.png)
)

Anyway, the client_id exists in the JWT a couple of times in other places, e.g. "aud" and "azp". 

Here how a JWT token from KeyCloak looks like:
```
{
  "jti": "5c7764dc-79b3-4be1-bc32-1b98cc9802db",
  "exp": 1519302089,
  "nbf": 0,
  "iat": 1519302029,
  "iss": "http://localhost:8080/auth/realms/demo",
  "aud": "openIdDemo",
  "sub": "680011c5-e53b-41b2-af15-8b6d89f1a00b",
  "typ": "Bearer",
  "azp": "openIdDemo",
  "auth_time": 1519301953,
  "session_state": "a9b3af16-5052-4c38-8c4c-c655ce5769f7",
  "acr": "0",
  "allowed-origins": [],
  "realm_access": {
    "roles": [
      "uma_authorization"
    ]
  },
  "resource_access": {
    "openIdDemo": {
      "roles": [
        "clientrole_admin"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "abc": "openIdDemo",
  "preferred_username": "animad_admin",
  "email": "a@b.de"
}
```

So, what I would wish for is some kind of parameter setting for `DefaultAccessTokenConverter`, where it could be influenced from where the client_id claim is taken in the JWT.

What do you think @dsyer ?

**Comment by dsyer** [comment]
Duplicates https://github.com/spring-projects/spring-security-oauth2-boot/issues/5?

**Comment by dsyer** [comment]
I can't figure out what's going on yet. If you have `@EnableOAuth2Sso` how come the inbound `OAuth2Authentication` doesn't have the client id? I don't see how that could happen unless you were eliding the details, and in fact you aren't using the `@EnableOAuth2Sso` feature at all, but decoding an incoming JWT token from somewhere. I would recommend using `@EnableOAuth2Sso` and I don't think you will have to worry about it then. Maybe you can provide a simple sample?

**Comment by rowe42** [comment]
Thanks for the quick reply!

No, not a duplicate to https://github.com/spring-projects/spring-security-oauth2-boot/issues/5
- There, is goes about a web application secured with `@EnableOAuth2Sso` (which happens to be a Zuul Gateway as well, but IMO not relevant for the issue), which does not refresh its JWT Access Token
- Here, it goes about the Zuul Gateway not being able to refresh the Access-Token while forwarding the call to a backend microservice
However, if we solve issue 5 there, it would make this issue much less severe.

My limited understanding:
- the inbound `OAuth2Authentication` is created in method `extractAuthentication` in https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/DefaultAccessTokenConverter.java
- for this the method `extractAuthentication` gets a `Map<String, ?> map`, where it picks the attributes and parameters needed to create the `OAuth2Authentication`
- this `Map<String, ?> map` contains everything the JWT token from the Auth Server contained, parsed into flat key-value-pairs (don't ask me where that happens, I didn't track that down).
- what I see from debugging is that this Map in our case does NOT contain a key-value-pair with key "client_id", but which the method  `extractAuthentication` is obviously expecting.

My guess is that a generic Spring-based OAuth2 Server does by default deliver such an entry "client_id" within the JWT token, but the KeyCloak server does not. However, reading the spec for JWT this is also not a specified content. But as I said, the KeyCloak does deliver the ClientId in other fields, e.g. "azp" or "aud".

So, what I have done as a workaround at the moment is derive a class from `DefaultAccessTokenConverter`, which in the overridden method  `extractAuthentication` does copy the content from "azp" into a new created entry "client_id".

However, what I would prefer is if there would be some kind of setting in `DefaultAccessTokenConverter`, where one could simply define where in the JWT the value for the ClientId can be found.

Does that make it a bit clearer what I am trying to say?

Of course I could provide a simple example, but in order to try it you would need to have a local installation of KeyCloak running and configured (which is not difficult, but takes a few minutes). Would you be willing to do that?

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
