### ISSUE TITLE
Provide Spring Cloud Security Parity Between Zuul and Spring Cloud Gateway

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-security#141]

**Comment by rapidwein** [comment]
Any statuses/updates on this? @dsyer

**Comment by Minisha** [comment]
Any updates on this?

**Comment by geercode** [comment]
@spencergibb ping...see u again.  :D .Does spring-security-oauth2 support spring-cloud-gateway.2.0.0.RELEASE?what about the version 5.0.x?
I was trying to adapt spring cloud Finchley.RELEASE with oauth2.Thoughts.plz.

**Comment by leiyazhen** [comment]
> @spencergibb ping...see u again. :D .Does spring-security-oauth2 support spring-cloud-gateway.2.0.0.RELEASE?what about the version 5.0.x?
> I was trying to adapt spring cloud Finchley.RELEASE with oauth2.Thoughts.plz.

@geercode hi,do you have resolved this problem?pls.

**Comment by geercode** [comment]
@leiyazhen nope.I cant fight with the framework.If you want to use spring oauth2 in gateway Finchley,Althougn there're two plans.
1.you could write a own-made oauth2 client to be a delegate and config a global filter.
```
ServerHttpRequest newRequest = exchange.getRequest().mutate().header("Authorizaiont", "Bearer ${token}").build();
ServerWebExchange newExchange = exchange.mutate().request(newRequest).build();
```
It's the most compitable way.
2.you could change spring-security-oauth2 to version 5.1.x and read [https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#webflux-oauth2](doc)
there's a big difference between 5.0.x and 5.1.x. Gonna need a good test.

**Comment by artemMartynenko** [comment]
@leiyazhen , after Spring Security 5.1.1 release I have found that there is enough functionality to provide OAuth2 SSO with Spring Cloud Gateway and reactive approach in the same manner as Zuul and servlet approach. There is a sample application which can be helpful. [spring-cloud-gateway-oauth2-sso-sample-application](https://github.com/artemMartynenko/spring-cloud-gateway-oauth2-sso-sample-application)

**Comment by geercode** [comment]
@artemMartynenko cool,under oauth2 protocol,they're supposed to work together,thx for your work and testing.

**Comment by wtatum** [comment]
First of all, huge thanks to the whole Spring team. What you guys are doing with 5.1 is awesome and I'm loving the reactive stack.

I'm hoping to get some clarification on what is considered 'in-scope' for this ticket. What I was hoping for is similar behavior to what's supported for Reactive WebClient in `org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction`. This class includes (optionally) automatic resolution of an authorized client, as well as getting a refresh token to get an updated access token if needed. It seems like this is precisely what would be wanted for a Gateway exchange as well, either as a filter function, or a global filter.

Is that part of the aim here? Is it expected to work for both OAuth clients as well as resource servers?

**Comment by spencergibb** [comment]
@wtatum the features this is focused on live here https://github.com/spring-cloud/spring-cloud-security/tree/master/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/proxy

**Comment by wtatum** [comment]
Thanks for the quick reply @spencergibb . I think the OAuth2TokenRelayFilter describes the scenario I'm interested in. I'm curious to see how this will carry over to 5.1 and Reactive. The existing Zuul filter cares about
```java
if(auth instanceof OAuth2Authentication)
```
From the testing I've done on putting my own implementation in for now, the runtime type depends on exactly which OAuth scenario is implemented (Resource Server, OAuth 2.0 with auth code, or OIDC). For me I think having the gateway also act as an OAuth client--so it can perform auth code flow for web clients that aren't OAuth aware--makes the most sense, but I've seen others use the gateway as a resource server instead.

**Comment by mraible** [comment]
@spencergibb Sorry to comment on a closed issue, but https://github.com/spring-cloud/spring-cloud-security/tree/master/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/proxy seems to only support Spring Security 5 when using `OAuth2AuthenticationDetails`. 

I'm trying to use Spring Security 5.1 and its oauth2Login()/oauth2ResourceServer() with `OAuth2AuthenticationToken`. Is there any documentation on how to relay the access token to downstream microservices when using Spring Security 5.1?

**Comment by ryanjbaxter** [comment]
@mraible I am not sure you are in the right place.  This might help https://docs.spring.io/spring-security/site/docs/current/reference/html/webflux-oauth2.html

If not sounds like you might want to pose your question in Spring Security https://github.com/spring-projects/spring-security

**Comment by mraible** [comment]
I figured it out. I was lazy initializing the `ZuulFilterInitializer` (or something like that).
