### ISSUE TITLE
spring oauth2.0 login page unauthorized

### ISSUE THREAD

**Issue by godpit** [spring-cloud/spring-cloud-security#144]
<img width="532" alt="wx20180321-105137 2x" src="https://user-images.githubusercontent.com/34534331/37692812-0d7b2216-2cf6-11e8-85e6-1ae99ccb4754.png">
spring cloud + security oauth 2.0, login-page url is unauthorized,i needn't the url  that is authorized. When the login is successful， get token, and authorized successfully.

**Comment by spencergibb** [comment]
@godpit please provide more information. What is your configuration, what version of spring cloud are you using? 

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by godpit** [comment]
spring cloud Finchley.M7,
<img width="830" alt="wx20180321-111526 2x" src="https://user-images.githubusercontent.com/34534331/37693269-72bcb588-2cf9-11e8-828a-1dd478be1c37.png">
<img width="938" alt="wx20180321-111453 2x" src="https://user-images.githubusercontent.com/34534331/37693276-7accb7fa-2cf9-11e8-8d78-75bc312f476e.png">
class WebSecurityConfig extends WebSecurityConfigurerAdapter,

**Comment by spencergibb** [comment]
Please don't past screenshots.

**Comment by spencergibb** [comment]
> Can you provide a complete, minimal, verifiable sample that reproduces the problem?

**Comment by godpit** [comment]
A little difficult to provide，Please tell me if I can enter the login page without authorization.

**Comment by godpit** [comment]
i enter the url of 'http://localhost:9060/oauth/authorize', it redirect to http://localhost:9060/login.but it show me  unauthorized

**Comment by godpit** [comment]
i got it, by adding the matcher of url  '/login'.


@Configuration
@EnableResourceServer
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.csrf().disable()
                .exceptionHandling()
                .authenticationEntryPoint((request, response, authException) ->
                        response.sendError(HttpServletResponse.SC_UNAUTHORIZED)
                ).and()
                .authorizeRequests().antMatchers("/login").permitAll()
                .anyRequest().authenticated()
                .and()
                .httpBasic();
    }
}

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
