### ISSUE TITLE
SessionCreationPolicy.STATELESS

### ISSUE THREAD

**Issue by gengxiaoxiaoxin** [spring-cloud/spring-cloud-security#147]
I try to build a stateless session application by cloud oauth2.
this is the zuul service：
```java
@Configuration
@EnableOAuth2Sso
public class Oauth2ClientServerConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		//@formatter:off
		http.csrf().disable()
				// STATELESS
		                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                                .and()
				.antMatcher("/**").authorizeRequests()
				// Allow access to all static resources without authentication
				.antMatchers("/", "/favicon.ico").permitAll()
                                .anyRequest().authenticated();
	        //@formatter:on
	}
}
```
The **SavedRequestAwareAuthenticationSuccessHandler** is not working so that zuul service can’t redirect to callback url。

**Comment by spencergibb** [comment]
Zuul has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
