### ISSUE TITLE
Will spring cloud security supports reactive feature and netty container?

### ISSUE THREAD

**Issue by jeven2016** [spring-cloud/spring-cloud-security#148]
Hi team,
  As you know, spring cloud security is implemented with spring mvc and embedded tomcat is used. Is any plan to support some new features of spring boot2 & spring5?  especially for the webFlux and netty instead of tomcat.

Thanks

**Comment by jeven2016** [comment]
>org.springframework.boot:**spring-boot-starter-tomcat**:2.0.1.RELEASE (selected by rule)
    >org.springframework.boot:spring-boot-starter-web:2.0.1.RELEASE
      > org.springframework.cloud:spring-cloud-security:2.0.0.M3
       >  org.springframework.cloud:spring-cloud-starter-security:2.0.0.M3
        > org.springframework.cloud:spring-cloud-starter-oauth2:2.0.0.M3
        >  compile

**Comment by yqbjtu** [comment]
I found that spring cloud gateway can't work with oauth for gateway uses netty and oauth uses tomcat.
Do we have any plan to support  reactive feature and netty container?  Thank you!

**Comment by spencergibb** [comment]
Closed, see #141
