### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by mkozik-at-comarch** [spring-cloud/spring-cloud-security#151]
Hi all,
We are using the spring-cloud-security as it is licensed under Apache-2.0, however our legal requires copyright information. I did not found any information, but the comment in java file stating that "Copyright 2013-2014 the original author or authors." which is sufficient.

Could someone eligible (don't know if it is proper wording) add information about copyright - preferably as separate COPYRIGHT file, reference in README, or even as response to this ticket?
Is it Dave Syer, author of first commit in this repo, with contributors, or copyright goes to Pivotal?

Thank you
Best regards
Michal

**Comment by spencergibb** [comment]
Our copyright is the header in the individual source files.
