### ISSUE TITLE
OAuth2FeignRequestInterceptor is thread safe?

### ISSUE THREAD

**Issue by metalpalo** [spring-cloud/spring-cloud-security#153]
Hi all,
  
I have one question.

I would like to use OAuth2FeignRequestInterceptor for my feign client together with DefaultOAuth2ClientContext which is not thread safe.

My interceptor can be fired from multiple threads, not from request. In this case the  DefaultOAuth2ClientContext is not session scoped as in spring framework.

What in that case when 10 threads try to concurrently get token via interceptor. I think the last thread wins and rewrite token in  DefaultOAuth2ClientContext objects and in the worst case the token will be acqruired ten times.

Am I right?

My configuration class is here:

```
@Configuration
public class FeignClientConfiguration {

    @Bean
    public RequestInterceptor requestInterceptor(ApplicationContext ctx)
    {
        return new OAuth2FeignRequestInterceptor(new DefaultOAuth2ClientContext(), clientCredentialsResourceDetails(ctx));
    }

    private static ClientCredentialsResourceDetails clientCredentialsResourceDetails(ApplicationContext ctx) {
        ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
        details.setAccessTokenUri(ctx.getEnvironment().getProperty("tokenUrl"));
        details.setClientId(ctx.getEnvironment().getProperty("clientId"));
        details.setClientSecret(ctx.getEnvironment().getProperty("clientId"));

        return details;
    }
}
```

**Comment by spencergibb** [comment]
I believe it is. Have you experienced otherwise?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by metalpalo** [comment]
sorry for late answer.

If I understood your anwer, interceptor is thread safe right? Can you tell me which part implement such synchronization or something else?

thanks

**Comment by spencergibb** [comment]
There is no specific synchronization.
