### ISSUE TITLE
Make EnableOAuth2Sso.class part of the spring-cloud-security artifact

### ISSUE THREAD

**Issue by nucatus** [spring-cloud/spring-cloud-security#154]
I guess it is more intuitive and less error prone to have EnableOAuth2Sso.class being part of the `spring-cloud-security` instead of `spring-security-oauth2-autoconfigure`.

You may end-up in a situation where you have `spring-security-oauth2-autoconfigure` on the classpath, but not `spring-cloud-security`, code compiles fine, and still EnableOAuth2Sso being useless. 

On the other hand, since `spring-security-oauth2-autoconfigure` is a dependency of `spring-cloud-security`, you may be pretty sure that once you have EnableOAuth2Sso in the code and that compiles fine, it should work.

**Comment by spencergibb** [comment]
It's going to stay where it is.
