### ISSUE TITLE
In FeignClients, using authorization_code type for Oauth2 authentication, how to pass OAuth2FeignRequestInterceptor OAuth2ClientContext information?

### ISSUE THREAD

**Issue by hceny-architect** [spring-cloud/spring-cloud-security#156]
I use authorization_code for OAuth2 authentication. Without going through FeignClient, there is no problem to access Client directly.

However, when using microservice calls via FeignClient, I used the org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor class, which is always a 401 authentication error. After I used DefaultOAuth2ClientContext, the link was redirected.

However, there is an error [error="invalid_request", error_description="A redirect_uri must be supplied."]. See a request.setCurrentUri, but do not know what link is set?

Or do I need to get the current context in any other way.

PS：I have assisted with some translations through translation tools, and I hope for understanding if there are any problems.

The following are the various configurations and codes：

`public class OAuth2FeignAutoConfiguration {
	public OAuth2ClientContext oAuth2ClientContext() {
		DefaultAccessTokenRequest request = new DefaultAccessTokenRequest();
		return new DefaultOAuth2ClientContext(request);
	}

	@Bean
	public RequestInterceptor oauth2FeignRequestInterceptor(OAuth2ClientContext oauth2ClientContext, BaseOAuth2ProtectedResourceDetails resource) {
		return new OAuth2FeignRequestInterceptor(oauth2ClientContext, resource);
	}

	@Bean
	public Logger.Level feignLoggerLevel() {
		return Logger.Level.FULL;
	}
}

@Configuration
@EnableResourceServer
public class ResourceServerConfigurer extends ResourceServerConfigurerAdapter {
	@Override
	public void configure(HttpSecurity http) throws Exception {
		http.authorizeRequests().anyRequest().authenticated();
	}
}

@EnableFeignClients
@EnableDiscoveryClient
@EnableOAuth2Sso
@SpringBootApplication
public class ServiceFeignApplication {
	public static void main(String[] args) {
		SpringApplication.run(ServiceFeignApplication.class, args);
	}
}

@FeignClient(value = "service-index", configuration = OAuth2FeignAutoConfiguration.class)
public interface SchedualService {
	@RequestMapping(value = "/client/test", method = RequestMethod.GET)
	String indexFormService();
}`

**Comment by Angel-King** [comment]
@sleepiejohn @dsyer @spencergibb Hello, can you help me solve my doubts? I spent nearly a month searching for a lot of information on the Internet and could not solve it.

**Comment by hceny-architect** [comment]
Who can help me to answer, thanks

**Comment by ray0728** [comment]
@hceny How did you fix this problem?
