### ISSUE TITLE
import  OAuth2FeignRequestInterceptor but I get an exception when I start the project.

### ISSUE THREAD

**Issue by wangzhangmao** [spring-cloud/spring-cloud-security#157]
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.client.DefaultOAuth2ClientContext' available: expected at least 1 bean which qualifies as autowire candidate
![3 x2 kw2 9dn8xflg7 j](https://user-images.githubusercontent.com/18365870/42624682-90ea3136-85f8-11e8-989a-49deda2aa50b.png)
![eb b 3qtavjfkbmp ad6t p](https://user-images.githubusercontent.com/18365870/42624683-91319ae4-85f8-11e8-9a08-7d7bd7761000.png)

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
