### ISSUE TITLE
nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V

### ISSUE THREAD

**Issue by yy306525121** [spring-cloud/spring-cloud-security#158]
hello sir,
![image](https://user-images.githubusercontent.com/12985872/42669914-a61f29ca-868a-11e8-8b57-f4c7a1cd50b2.png)
it is 2.2.1.RELEASE， and the RedisTokenStore.java is 
![image](https://user-images.githubusercontent.com/12985872/42669940-c02a7f90-868a-11e8-94b3-3160c2ac7a15.png)
and since 2.3.1.RELEASE it is
![image](https://user-images.githubusercontent.com/12985872/42669972-e61f8c7c-868a-11e8-984a-95380ca59524.png)

**Comment by spencergibb** [comment]
Those projects are not maintained here.
