### ISSUE TITLE
OAuth2 can't work with Spring Cloud gateway

### ISSUE THREAD

**Issue by yqbjtu** [spring-cloud/spring-cloud-security#162]
Cloud we add support for spring cloud gateway?

it means that spring cloud security needs to support reactive feature and netty container.

you can this https://github.com/spring-cloud/spring-cloud-gateway/issues/478.

Notes:
When the gateway runs standalone, it starts netty, works well.
When my oauth runs standalone,it starts tomcat, works well.
but it can't work when integrationg spring cloud gateway with OAuth.

**Comment by spencergibb** [comment]
Duplicates #141
