### ISSUE TITLE
Eureka cluster can't copy another server

### ISSUE THREAD

**Issue by zl7261** [spring-cloud/spring-cloud-security#163]
I create an eureka cluster with two sever,port 8001 and 8002.
And disable crsf, use username;password@eurekaAddress:port to registry micro service.

It's ok, but I found when I import spring-cloud-security to protect eureka page access.
The service which already registry to an eureka server will not copy to another eureka sever.
Both of them in a same cluster.
If I remove security,them copy services as well.

It's there something else should I disable?

**Comment by spencergibb** [comment]
Spring Cloud security does not secure eureka and is unrelated.
