### ISSUE TITLE
OAuth2RestOperations ClassNotFoundException at runtime

### ISSUE THREAD

**Issue by maxiwu** [spring-cloud/spring-cloud-security#166]
I have a Zuul project and try to add OAuth2 to secure the gateway.
My gateway is build on 
spring-boot-starter-parent 1.5.13.RELEASE and spring cloud netflix Edgware.SR4.

After adding dependency spring-cloud-security and annotation @EnableOAuth2Sso.
It throws ClassNotFoundExcpetion on start.

> Caused by: java.lang.ClassNotFoundException: org.springframework.security.oauth2.client.OAuth2RestOperations
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more

What is the correct dependency of spring cloud security to work with Edgware.SR4?

**Comment by spencergibb** [comment]
Answered in #167
