### ISSUE TITLE
How to add a custom tokenGranter bean，for example I want to add a custom tokenGranter named MobileTokenGranter ，it can get access_token from user's sms code to authencate

### ISSUE THREAD

**Issue by 99bird** [spring-cloud/spring-cloud-security#211]

**Comment by ryanjbaxter** [comment]
Can you please provide a better description of the problem and also provide a sample that reproduces the issue?

**Comment by 99bird** [comment]
![image](https://user-images.githubusercontent.com/38944065/57635934-c9c59400-75da-11e9-87fb-5fb6476929fe.png)
I want add a custom TokenGranter，but I don't how config it

**Comment by 99bird** [comment]
![image](https://user-images.githubusercontent.com/38944065/57636424-ad762700-75db-11e9-8632-9130c5c104c1.png)
The TokenGranter bean is fixed , it can't custom config it

**Comment by spencergibb** [comment]
That's really a spring security question isn't it?

**Comment by 99bird** [comment]
![image](https://user-images.githubusercontent.com/38944065/57657680-a61c4100-760e-11e9-9a55-e0d4fe07a005.png)
I'm not sure whether this is allowed.  I want add a custom tokenGranter to the tokenGranter list . it can do something like other tokenGranter beans

**Comment by spencergibb** [comment]
I don't know either, please ask in spring security.
