### ISSUE TITLE
OAuth2FeignRequestInterceptor should clear exist Authorization header

### ISSUE THREAD

**Issue by abccbaandy** [spring-cloud/spring-cloud-security#212]
spring boot : 2.1.5.RELEASE
spring cloud : Greenwich.SR1

I think `OAuth2FeignRequestInterceptor` should clear exist Authorization header, because if there is a exist header(ex: when retry by feign Retryer), it will append the new token to exist token, cause auth failed.

Currently workaround :
````java
public class OAuth2FeignRequestInterceptor2 extends OAuth2FeignRequestInterceptor {

    public OAuth2FeignRequestInterceptor2(OAuth2ClientContext oAuth2ClientContext, OAuth2ProtectedResourceDetails resource) {
        super(oAuth2ClientContext, resource);
    }

    @Override
    public void apply(RequestTemplate template) {
        //clear all exist Authorization header
        template.header(AUTHORIZATION);
        super.apply(template);
    }
}
````

**Comment by TYsewyn** [comment]
Hi @abccbaandy, thank you for your issue! This should be fixed in the next service release of Greenwich.
