### ISSUE TITLE
What's the difference between spring cloud security and spring boot security

### ISSUE THREAD

**Issue by SparkZhou1994** [spring-cloud/spring-cloud-security#215]
Question
What's the difference between 'spring-cloud-security' and 'spring-boot-security'?
Can 'spring-boot-security' be used in the spring cloud project?
Is it essential to learn 'spring-cloud-security' after learning 'spring-boot-security'?

Thank you for replying.

**Comment by spencergibb** [comment]
Spring cloud security adds a few security features to zuul, feign and gateway. It is not a replacement for spring security
