### ISSUE TITLE
Upgrade to correct spring-security-oauth2-autoconfigure version

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-security#218]
This should be a one from 2.2.x which uses same boot deps.
https://github.com/spring-cloud/spring-cloud-security/blob/b5cf6e709a1d4a6b84f59b9347fba567e4c50b27/spring-cloud-security-dependencies/pom.xml#L17

**Comment by jvalkeal** [comment]
Paging @spencergibb as this probably slipped throught.

**Comment by ryanjbaxter** [comment]
Duplicate of #217
