### ISSUE TITLE
@EnableOAuth2Resource requires oauth2.client.clientId

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-security#22]
So maybe I am missing something here.  I am trying to create an API-Gateway service.  It is configured with the oauth client information.  I have a separate service acting as the authorization service, it configures that client (the api gateway) to be able to access multiple resources.  On my resource I do not want to configure a client, just the resource id and the jwt endpoint.  Yet I cant because that annotation requires a client id.

In the docs it says this:

```
The @EnableOAuth2Resource annotation will protect your API endpoints if you have the same environment settings as the SSO client, except that it doesn’t need a tokenUri or authorizationUri, and it also doesn’t need a clientId and clientSecret if it isn’t using the tokenInfoUri (i.e. if it has jwt.* or userInfoUri).
```

This implies to me that I shouldn't need it.  I am thinking of the case where the resource does not have the need to act as a client at all.  Once I get everything in a halfway working state I can upload an example but let me know if I am missing something here.

**Comment by dsyer** [comment]
The docs should be correct in principle. An integration test would be helpful if you want to help.

**Comment by dsyer** [comment]
Here's a sample (one of a series of related samples I was planning on turning into some blogs): https://github.com/dsyer/security-micro-clients/tree/master/oauth2. I did make some changes to the resource server configuration in Spring Cloud, but I think this sample would have worked with RC1 with a bit of manual configuration of the secure paths in the UI.

**Comment by wgorder** [comment]
Thanks Dave.  I am working on a sample that integrates all these concepts and spring-cloud modules mostly for my own understanding.  Its still a a WIP (but making progress :) ).   Once its done I will run it by you and if you think it would be useful I would be more then happy to contribute it to wherever
