### ISSUE TITLE
Question about AccessDecisionManager in spring cloud gateway

### ISSUE THREAD

**Issue by dailin** [spring-cloud/spring-cloud-security#221]
I use AccessDecisionManager and AbstractSecurityInterceptor to access control, it works well with zuul, but now changed to spring cloud gateway which use webflux, and i don't know how to implement  AbstractSecurityInterceptor with webflux version

**Comment by spencergibb** [comment]
`AccessDecisionManager` is from spring-security. It would be better to ask there or in their gitter https://gitter.im/spring-projects/spring-security
