### ISSUE TITLE
Do you have oauth2 migration demo?

### ISSUE THREAD

**Issue by chehongwei-git** [spring-cloud/spring-cloud-security#228]
Excuse me, is there an example of integrating SSO with spring cloud security? Didn't understand the migration guide. Thanks

**Comment by ryanjbaxter** [comment]
You will need to provide more information for what you are looking for

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
