### ISSUE TITLE
Configure AuthenticationEntryPoint with @EnableOAuth2Sso

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-security#23]
From what I can see in the OAuth2SsoConfiguration class the http.exceptionHandling().authenticationEntryPoint and logout configurer are completed after my configurers so there is no way for me to return a 401 when a login is required.  In my SPA application I don't want to receive 'found' or redirects but rather a 401 so that the Angular application can display the login page.

**Comment by dsyer** [comment]
I'm sure you can detect the signature of the redirect in Angular (e.g. you will see HTML coming back instead of JSON), but I agree in principle that a 401 might be useful. Not sure what you meant about "my configurers" though.

**Comment by wgorder** [comment]
Yes you are correct you could do that as well.  I was simply stating that the below block happens before the aforementioned configuration is done, so the only way to override it really is to subclass and override the entire method.

```
for (OAuth2SsoConfigurer configurer : configurers) {
			// Delegates can add authorizeRequests() here (and if they add more matchers
			// those will override the ones added above)
			configurer.configure(http);
		}
```
