### ISSUE TITLE
Use ClientId and ClientSecret for token refresh

### ISSUE THREAD

**Issue by rcbandit111** [spring-cloud/spring-cloud-security#241]
I want to implement OAuth2 token refresh without basicAuth authentication using spring-cloud-starter-oauth2.

I'm forced to use basicAuth for token refresh. If I remove it I get error:

`    "error_description": "There is no client authentication. Try adding an appropriate authentication filter."
`

Is there some way to avoid this authentication for refresh token? For example is it possible to use `ClientId` and `ClientSecret`? 

Are there any possible options to solve this issue? I'm really stuck with this issue.

  [1]: https://github.com/rcbandit111/OAuth2/blob/master/src/main/java/org/engine/security/WebSecurityConfig.java#L43

**Comment by ryanjbaxter** [comment]
Can you explain what this has to do with Spring Cloud Security?  Maybe if you provided a sample it would help.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
