### ISSUE TITLE
TokenRelayGatewayFilterFactory is a deprecated class only in spring-cloud-security.2.2.2.RELEASE

### ISSUE THREAD

**Issue by revoorunischal** [spring-cloud/spring-cloud-security#244]
TokenRelayGatewayFilterFactory is a deprecated class only in spring-cloud-security.2.2.2.RELEASE and since this is the version added from spring-boot-starter-parent2.3.2.RELEASE, I do not want to change it manually.  Is there any specific reason why this was deprecated only in this particular release? 

And what is the alternate to TokenRelayGatewayFilterFactory in spring-boot-starter-parent2.3.2.RELEASE ?

**Comment by spencergibb** [comment]
it will be migrating to a new project in 3.0.x (it has nothing to do with the boot version btw).
