### ISSUE TITLE
If oauth2 token issued at time and system time difference is more than 60secs, necessary logs are not captured.

### ISSUE THREAD

**Issue by ajaythompson** [spring-cloud/spring-cloud-security#246]
If oauth2 token issued at time and system time difference is more than 60secs, necessary logs are not captured.
Error log to be captured for invalid claims.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
