### ISSUE TITLE
@AuthorizationServer And @Configuration

### ISSUE THREAD

**Issue by hongji3354** [spring-cloud/spring-cloud-security#248]
@EnableWebSecurity has @Configuration, so just adding @EnableWebSecurity allows automatic setup, but @EnableAuthorizationServer does not have @Configuration, so you need to add @Configuration to proceed with the auto setup.

Generally, when using @Enable-related annotations, we think that using only that annotation will lead to automatic setup, so we would also like to add @Configuration to @EnableAuthorizationServer

**Comment by spencergibb** [comment]
how does this apply to this project?

**Comment by hongji3354** [comment]
I wish there was @Configuration in the @EnableAuthorizationServer annotation, just as there is @Configuration in the @EnableWebSecurity annotation.

Use only the @EnableAuthorization Server annotation to proceed with the automatic setup.

**Comment by spencergibb** [comment]
`@EnableAuthorizationServer` is part of https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/EnableAuthorizationServer.java. Open an issue there as I can't transfer issues across orgs.

**Comment by hongji3354** [comment]
Thank you.
