### ISSUE TITLE
Can't get @EnableOAuth2Sso to trigger in test case

### ISSUE THREAD

**Issue by jghiloni** [spring-cloud/spring-cloud-security#31]
I'm currently using `@EnableOAuth2Sso` and `@EnableOAuth2Resource` as meta-annotations on an abstracted security library we're writing, and I'm having some issues in the unit tests. I'm fairly certain this isn't a code issue, just a PEBCAK issue, but I'm wondering how I can test that these annotations are importing the correct configuration in a JUnit configuration? I can see that security is being applied, but in cases where I expect to be redirected to the log in page, I get a 401 with Basic in the WWW-Authenticate header.

**Comment by dsyer** [comment]
Basic is probably wrong. `@EnableOAuth2Resource` sends a WWW-Authenticate with `Bearer` and `@EnableOAuth2Sso` sends a 302 to unauthenticated requests. The most likely explanation is that you don't have the right `spring.oauth2.*` properties configured in your test. If you are using a `SpringApplication` (e.g. with `@SpringApplicationConfiguration`) then you can add a `debug=true` to see the autoconfig report and find out whether the configuration has been applied and if not why not.

**Comment by jghiloni** [comment]
Thanks Dave. I will look into that shortly and let you know what I find.

**Comment by jghiloni** [comment]
Well, I was right. It was PEBCAK :) Because my meta-annotations can exist at the type or method level, my test case had them at the method level and as such, the spring processor was not finding them. If I moved them to the type level, things worked as I expected them to. Thanks for the debug=true tip, and I'll figure out a way to post-process my `@Controller` beans to pick up the annotations on the methods.
