### ISSUE TITLE
How to provide custom redirect_uri when using @EnableOAuth2Sso

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-security#32]
Hello,

I am using the OAuth2 module and Spring Cloud Zuul to proxy service requests.  The plan would be to have Zuul redirect to the Authorization Server using a redirect_uri of the previous request.  However, due to the Spring Security redirect to /login I always get sent back to login.   In a perfect world the redirect uri would be the original request to the Zuul Proxy.  Is there a way to provide this functionality?

**Comment by dsyer** [comment]
The way SpringSecurity works you should get a redirect back to the original page that triggered the login (not an OAuth or a Spring cloud feature). Maybe you could describe your use case a bit more, or provide a sample, or (even better) refer to one of the existing samples?

**Comment by NickPadilla** [comment]
Hey @dsyer  You are right, i was being thrown off by the fact that the redirect_url was always http://127.0.0.1:8765/login instead of the hystrix service.  But it does get sent to the correct url after authentication.  It just threw me off.  Thanks for the clarification.

**Comment by zhl-home1** [comment]
I got the same issue!
When I access the ui server the redirect chain is '/' ->  '/index.html' -> '/login' -> authserver '/login' -> authserver '/oauth/authorize' (redirect_uri is uiserver '/login') -> uiserver '/login'.
How can I get rid of this? Please help!
I think the authenticationEntrypoint on ui server should pass correct /index.html to authserver on redirection. Am I wrong?

**Comment by t-my** [comment]
Hey @dsyer and @NickPadilla, I have a question regarding this issue:

I'm running behind apache reverse proxy in url.com/application and the application runs at host:8080. Redirect_url loses the value /application and I'm being redirected  back to url.com after form login.

Here's my apache config: 

ProxyRequests Off
ProxyPreserveHost Off
ProxyPass /application http://hostname:8080
ProxyPassReverse /application http://hostname:8080

I appreciate any help, thanks!

**Comment by dsyer** [comment]
With Tomcat use the `RemoteIpValve` (there's a section in the boot user guide).

**Comment by t-my** [comment]
Thanks! Do you know if there's anything similar for undertow since I've been using it.

**Comment by dsyer** [comment]
I expect so. I know jetty has it (as a handler that can be added).
