### ISSUE TITLE
How to override RemoteTokenServices

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-security#37]
Hello again! 

I am using `@EnableOAuth2Sso` functionality and as our testing/integration has moved forward it has been found that it would be best to provide our own `RemoteTokenServices` implementation.  Right now that is being configured using `ResourceServerTokenServicesConfiguration` and `TokenInfoServicesConfiguration` gets registered.  How do i register the custom implementation?

**Comment by dsyer** [comment]
That's not currently supported with the `@Enable*` annotations (so you'd have to pull in the various bits that they do yourself). What do you need your custom token services to do?

**Comment by NickPadilla** [comment]
Hey @dsyer - I appreciate your response! Yeah, so I guess I am not missing anything this time!  As the integration with Keycloak has advanced, we realized that having Keycloak verify/decode the access tokens was the most secure route to go.  However it looks like the verify/decode endpoint is a GET not POST.  So providing a custom RemoteTokenService would be the way to go.

**Comment by jesse-russell** [comment]
I'm actually having the same issue with ForgeRock's OpenAM right now. Any progress on this feature?

**Comment by dsyer** [comment]
These features moved to Spring Boot. If you need anything please open tickets there now (it looks to me like you can probably add a `@Bean` of type `ResourceServerTokenServices` to override though).

**Comment by levik666** [comment]
Hi @dsyer 

I understand that we could implement ResourceServerTokenServices. However what value we exposed to decouple RemoteTokenServices and we could extend it (make it protected not private). 

For instance, I have error when I call 
```
restTemplate.exchange(path, HttpMethod.POST,
				new HttpEntity<MultiValueMap<String, String>>(formData, headers), Map.class)
```

and without try catch, I don't get responseBody. In addition to that, I could override DefaultResponseErrorHandler I don't get the information from it.

```
try {
            return restTemplate.exchange(path, HttpMethod.POST,
                            new HttpEntity<>(formData, headers), Map.class).getBody();
        } catch (RestClientException exe) {
            if (exe instanceof HttpClientErrorException) {
                String responseBodyAsString = ((HttpClientErrorException) exe).getResponseBodyAsString();
                logger.error("Can't path " +  path + " responseBodyAsString " + responseBodyAsString);
            }
            throw exe;
        }
```

Could you please explain why we have such protection in this service, or maybe I miss something? 

I'll be really appreciated for any clarification

Thanks,

**Comment by dsyer** [comment]
This issue is closed. Read the comments (e.g. "These features moved to Spring Boot.").
