### ISSUE TITLE
Best way to provide oauth2 login redirect 

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-security#38]
I am wondering if there was a way to trigger a redirect to the oauth2 authentication server.  I am implementing a custom `RemoteTokenServices` and want to trigger the redirect if the token is invalid.  This would be just a first step to getting full refresh access token functionality added.

**Comment by dsyer** [comment]
That should be automatic if you are using `@EnableOAuth2Sso` (or the equivalent setup with `OAuthCientAuthentciationFilter`). If the token is invalid the client will throw a `UserRedirectRequiredException`.

**Comment by NickPadilla** [comment]
Hello @dsyer - Thanks again for your prompt response!  From what I see, the DefaultTokenServices and RemoteTokenServices both throw a `InvalidTokenException` which gets caught by the `OAuth2AuthenticationProcessingFilter` and that calls the `AuthenticationEntryPoint.commence`.  The exception that `commence` is given is a `InsufficientAuthenticationException` which extends `AuthenticationException`.  

So what it looks like i need to do is to throw a `UserRedirectRequiredException` when i find a token is invalid.  

Currently I just get the error page that shows the "Access token expired: {token}" message.  No redirect ever takes place.  Maybe b/c I am using `@EnableOAuth2Sso` and `@EnableZuulProxy` together?

**Comment by NickPadilla** [comment]
Ok so, I didn't change anything on my end to affect this - but it is now redirecting and not showing the error xml.  I did clear my local maven repository because of another issue - so maybe I had a stale version.
