### ISSUE TITLE
Add the option to have OAuth2RestTemplate use @LoadBalanced

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-security#51]
Possibly also create a non `@LoadBalanced` `OAuth2RestTemplate`.

**Comment by spencergibb** [comment]
related to #48

**Comment by sankarbalu** [comment]
I see that OAuth2RestTemplate still does not have the @LoadBalanced option as of spring cloud commons 1.1.0.M5. Any updates on this?
