### ISSUE TITLE
Ability to replace/configure the default success/failure handler in OAuth2ClientAuthenticationProcessingFilter

### ISSUE THREAD

**Issue by florinn** [spring-cloud/spring-cloud-security#55]
I have a Spring Boot app acting as a gateway to a SPA. The gateway main class is decorated with `@SpringBootApplication`, `@EnableZuulProxy` and `@EnableOAuth2Sso`

I'd like to host the SPA on a dedicated server (I'm using a Gulp toolchain to develop the SPA) and on successful authentication the gateway to redirect back to the SPA.

I'm trying to achieve this by having the SPA make login requests to a bogus gateway endpoint requiring authentication and consequently kicking off the `ExceptionTranslationFilter`
To make the redirect back to the SPA I assumed I could configure `OAuth2ClientAuthenticationProcessingFilter` to use as success handler a `SavedRequestAwareAuthenticationSuccessHandler` with the `useReferer` option enabled

Is there a way to replace/configure the default success/failure handler in `OAuth2ClientAuthenticationProcessingFilter`?

**Comment by spencergibb** [comment]
'SPA' = Single Page App?

**Comment by florinn** [comment]
Yes, that's what I meant by SPA

**Comment by dsyer** [comment]
I would assume you could add a `OAuth2SsoConfigurerAdapter` and set up the exception handling (overriding the defaults). Did you try that and it didn't work?

I'm also interested in understanding the use case in more detail (so is @scottfrederick). What do you mean by a "bogus gateway"? What is the advantage of `useReferer`?

**Comment by florinn** [comment]
@dsyer Starting from your [oauth2-vanilla](https://github.com/dsyer/spring-security-angular/tree/master/oauth2-vanilla) sample, I want to host an AngularJS app (I refer to it as "SPA") on a dedicated server (at least for development) and not directly on the gateway server as in your sample.

In my project the SPA is hosted on a server at `localhost:9000`, the gateway server is at `localhost:8080` and a "login" button in the SPA points to `localhost:8080/foo` (this would be the "bogus gateway endpoint" I mentioned earlier... not using `localhost:8080/login` because I want `ExceptionTranslationFilter` to kick in and put the request into the cache so that it can be retrieved later by `SavedRequestAwareAuthenticationSuccessHandler`).

For the gateway I tried the folowing configuration within a `OAuth2SsoConfigurerAdapter`:

```java
SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
successHandler.setUseReferer(true);
			
http
	.formLogin().successHandler(successHandler)
.and()
	.logout()
.and()
	.antMatcher("/**").authorizeRequests()
	.antMatchers("/index.html", "/home.html", "/", "/login").permitAll()
	.anyRequest().authenticated()
.and()
	.csrf()
	.csrfTokenRepository(csrfTokenRepository()).and()
	.addFilterAfter(csrfHeaderFilter(), CsrfFilter.class);
```

Following a successful login, the browser is redirected to `localhost:8080` and not to `localhost:9000` as I would like.
As far as I understand the success handler in `OAuth2ClientAuthenticationProcessingFilter` that gets called is still the default one and not the one specified in `OAuth2SsoConfigurerAdapter`.
What would be the right way to override the default success handler?

**Comment by florinn** [comment]
I also tried the following configuration with no success:

```java
final SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
successHandler.setUseReferer(true);
		
http
  .logout()
.and()
  .antMatcher("/**").authorizeRequests()
  .antMatchers("/index.html", "/home.html", "/", "/login").permitAll()
  .anyRequest().authenticated()
  .withObjectPostProcessor(new ObjectPostProcessor<OAuth2ClientAuthenticationProcessingFilter>() {
	public <O extends OAuth2ClientAuthenticationProcessingFilter> O postProcess(O fsi) {
				fsi.setAuthenticationSuccessHandler(successHandler);
				return fsi;
	}
})
.and()
  .csrf()
  .csrfTokenRepository(csrfTokenRepository()).and()
  .addFilterAfter(csrfHeaderFilter(), CsrfFilter.class);
```

**Comment by dsyer** [comment]
I'm not sure I understand the architecture yet. Why is the SPA not behind the gateway (see Part VI of the blog)?

**Comment by florinn** [comment]
The solution in Part VI of your blog should work fine if I move the SPA behind the gateway.
In my case I'd like to keep the gateway only for API's (the API gateway pattern in microservices architecture) and be able to call it from SPA, mobile and desktop clients.

So I guess what I'm asking could be reduced to this: 
Following a successful SSO login, is there a way to configure Spring Cloud Security to redirect to other target url besides localhost?

**Comment by Artgit** [comment]
I have the same question right now http://stackoverflow.com/questions/34692528/spring-security-oauth2-dance-and-get-parameters

I'm unable to redirect user to other location other than "/"

Do you have any solutions for this issue ?

**Comment by eshepelyuk** [comment]
Any updates on this ?

**Comment by dsyer** [comment]
All the OAuth SSO code moved to spring boot. I don't think there's anything stopping you from changing the filter configuration (we use a regular `WebSecurityConfigurer` there). But I also doubt you need to very often.

**Comment by VadimKirilchuk** [comment]
@dsyer Even though nothing prevents anyone to do something like:
    @Bean
    public SavedRequestAwareAuthenticationSuccessHandler savedRequestAwareAuthenticationSuccessHandler() {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        //TODO: this is a security hole, be careful allowing to pass ANY continueUrl
        //https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet
        **successHandler.setTargetUrlParameter("continueUrl");**
        successHandler.setUseReferer(true);
        return successHandler;
    }

	private Filter ssoFilter(OAuth2Configuration client, String path) {
	    OAuth2ClientAuthenticationProcessingFilter filter = new OAuth2ClientAuthenticationProcessingFilter(path);
	    OAuth2RestTemplate template = new OAuth2RestTemplate(client.getClient(), oauth2ClientContext);
	    filter.setRestTemplate(template);
	    filter.setTokenServices(new UserInfoTokenServices(
	        client.getResource().getUserInfoUri(), client.getClient().getClientId()));
	    **filter.setAuthenticationSuccessHandler(savedRequestAwareAuthenticationSuccessHandler());**
	    return filter;
	  } 

Don't you think it's worth adding to tutorial because I have almost the same situation as @florinn. I have a dedicated frontend and hidden(not available through web) backend. 
1. FE makes User Agent to call backend/login
1. User Agent redirected to facebook (whatever)
1. User authorizes our app
1. User Agent redirected to redirect_uri which is frontend/login?access_code=blah
1. Frontend proxies this call to backend/login?access_code=blah
1. Backend dances with OAuth2 to get access token
1. Once finished backend should redirect User Agent back to continueUrl, say frontend/user/profile

**Comment by dsyer** [comment]
Please don't append to closed issues. If there ever was a problem here, then now it's somewhere else.
