### ISSUE TITLE
Add support for Feign on OAuth2 protected resources

### ISSUE THREAD

**Issue by joaoevangelista** [spring-cloud/spring-cloud-security#56]
I'll be nice if we have some kind of support to include authorization on Feign requests, since I came across this issue, as asked on [StackOverflow](http://stackoverflow.com/questions/29439653/spring-cloud-feign-with-oauth2resttemplate/). I could fix it to my needs, thanks to @dsyer.

I can try to contribuite to this with my implementation, I just don't know how to test this with TDD :disappointed: 

[Here is the implemetation on a gist](https://gist.github.com/joaoevangelista/dc90bcea15da5f554c7c)

**Comment by spencergibb** [comment]
The other problem here is that feign config is currently all or nothing see #288

**Comment by joaoevangelista** [comment]
@spencergibb I can't follow the #288 link

**Comment by spencergibb** [comment]
fixed.  Your gist looks good btw. Testing is a bit difficult :-)

**Comment by joaoevangelista** [comment]
:blush: Thanks!

**Comment by cbornet** [comment]
The token is refreshed based on isExpired. Cannot there be some race conditions when requests are made close to the expiration ? Some other implementations also renew the token on HTTP 401 error but this cannot be done with request interceptor obviously.
