### ISSUE TITLE
@EnableOauth2Resource is disabling default user for actuator endpoints

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-security#57]
```@EnableOauth2Resource``` annotation is disabling default ```security.user```.
When I try to enter actuator endpoint with the user:password, it says:
``` o.s.s.w.a.www.BasicAuthenticationFilter  : Authentication request for failed: org.springframework.security.authentication.ProviderNotFoundException: No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken```

When ```security.user.password``` field is not specified, it would not log "Using default security password: ...".  ```AuthenticationManagerConfiguration``` is annotated ```@ConditionalOnMissingBean({ AuthenticationManager.class })``` & I assume ```ResourceServerConfiguration``` is registering authentication manager?

**Comment by leon** [comment]
Found the problem,
when the resource server is initiated, it calls
https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/ResourceServerConfiguration.java#L122

when the AuthenticationManagerConfiguration then gets it it’s configuration it will already be configured and will return early
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.java#L163

I'm not exactly shure on how to fix this, but I think it involves the resource server config calling
https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/authentication/builders/AuthenticationManagerBuilder.java#L81

**Comment by razvanfromoz** [comment]
Hi, did anybody find by chance a solution/workaround for this issue?

**Comment by beku8** [comment]
@razvanfromoz You can register custom GlobalAuthenticationConfigurerAdapter bean such like this:

```
public class InMemoryAuthenticationProvider extends GlobalAuthenticationConfigurerAdapter {
	private Logger logger = LoggerFactory.getLogger(getClass());
	@Autowired private SecurityProperties security;
	
	@Override
	public void init(AuthenticationManagerBuilder auth) throws Exception {
		User user = this.security.getUser();
		if (user.isDefaultPassword()) {
			logger.info("\n\nUsing default security password: " + user.getPassword()
					+ "\n");
		}
		Set<String> roles = new LinkedHashSet<String>(user.getRole());
		auth.inMemoryAuthentication().withUser(user.getName())
				.password(user.getPassword())
				.roles(roles.toArray(new String[roles.size()]));
	}
	
	

}
```

from your ```@Configuration``` class:
```
@Bean
public InMemoryAuthenticationProvider provider(){
  return new InMemoryAuthenticationProvider();
}
```

**Comment by razvanfromoz** [comment]
Thanks for the fast reply! Much appreciated!

**Comment by dsyer** [comment]
If you `@EnableOAuth2Resoucre` it is supposed to apply to all URL paths (i.e. the basic auth that you get out of the box for actuator endpoints would never be used). Isn't this kind of sensible? Anyway I don't see the same behaviour (I always get a 401 from Actuator endpoints if I don's send an access token). Can someone explain the difference?

**Comment by beku8** [comment]
In my case,  I apply ```oauth2``` to only specific segment of the url:

```
@Override
	public void configure(HttpSecurity http) throws Exception {
		http
			.requestMatchers()
			.antMatchers("/rest/**")
		.and()
			.authorizeRequests()
			.anyRequest().access("#tenant.hasManagerPermission()");
	}
```
Thus I suppose it should not "touch" anything else.
