### ISSUE TITLE
UserInfoTokenServices hardcodes authority to "ROLE_USER"

### ISSUE THREAD

**Issue by ncastilho** [spring-cloud/spring-cloud-security#62]
Hi there,

Having an issue with the UserInfoTokenServices. I've got a Resource Server configured using @EnableOAuth2Resource and I've setup the 'spring.oauth2.resource.userInfoUri' property to point to the '/me' endpoint on my separate Auth Server. From the logs, I see that the request, the 'OAuth2AuthenticationProcessingFilter' processes, successfully authenticates but with the 'Granted Authorities: USER_ROLE' even though my user doesn't have that role. 

In my 'HttpSecurity' on the 'ResourceServerConfigurerAdapter' class, I restrict access to my API based on 'ROLE_ADMIN' and as such I always get an 'Access Denied' response.

Had a look at the UserInfoTokenServices and when the UsernamePasswordAuthenticationToken is created in the extractAuthenticaton() method, the Collection<GrantedAuthority> is always set to: AuthorityUtils.commaSeparatedStringToAuthorityList("ROLE_USER")).

I had a go at implementing a method to extract the authorities from the 'userInfoEndpointUrl' response map:

    private String[] getAuthorities(Map<String, Object> map) {
        @SuppressWarnings("unchecked")
        List<Map<String, String>> authorityList = (List<Map<String, String>>) map.get("authorities");

        List<String> authorities = new ArrayList<>();
        for (Map<String, String> authority : authorityList) {
            authorities.add(authority.get("authority"));
        }
        return authorities.toArray(new String[] {});
    } 

This seems to work when I feed that into the UsernamePasswordAuthenticationToken:

    UsernamePasswordAuthenticationToken user = new UsernamePasswordAuthenticationToken(getPrincipal(map), "N/A", AuthorityUtils.createAuthorityList(getAuthorities(map)));

Is this an issue with the UserInfoTokenServices? Or am I just missing something in the configuration?

Cheers,
Nuno

**Comment by dsyer** [comment]
Thanks. This code moved to Spring Boot. Can you open an issue there please?
