### ISSUE TITLE
Example from documentation not working with Spring CLI v1.2.3.RELEASE

### ISSUE THREAD

**Issue by Endron** [spring-cloud/spring-cloud-security#64]
I am currently taking a look at Spring Cloud Security.

I copied the following code from the documentation:

    @Controller
    @EnableOAuth2Sso
    class Application {
        @RequestMapping('/')
            String home() {
            'Hello World'
        }
    }

When I try to run the code using Spring CLI v1.2.3.RELEASE on Mac OS X I get the error:

    startup failed:
    file:/Users/tobiaskremer/Documents/git-repos/portal/auth-service/app.groovy: 2: unable to resolve class EnableOAuth2Sso ,  unable to find class for annotation
     @ line 2, column 1.
       @EnableOAuth2Sso
       ^
    
    1 error

As I understand it Spring CLI should know what to include on the classpath based on the annotation. But this does not seam to work.

----
This could also be an issue with the Spring CLI (quite likely) but I report it here as the documentation is affected.

**Comment by spencergibb** [comment]
@Endron did you install the [Spring Cloud CLI](https://github.com/spring-cloud/spring-cloud-cli#installation)?

**Comment by Endron** [comment]
@spencergibb Of course not because I am stupid :smile: 

With the Spring Cloud CLI installed it works perfectly. Sorry!
Please close the issue.

**Comment by spencergibb** [comment]
@Endron no problem!  We'd like feedback.  Keep it coming.
