### ISSUE TITLE
Reference Documentation is offline

### ISSUE THREAD

**Issue by Endron** [spring-cloud/spring-cloud-security#66]
I just tried to access to reference documentation (http://cloud.spring.io/spring-cloud-config/spring-cloud-security.html) linked from the Spring.io website (http://cloud.spring.io/spring-cloud-security/). 

The links return 404. So the documentation is currently not available.

**Comment by dsyer** [comment]
Fixed thanks (it was a typo). It's all here as well though: http://projects.spring.io/spring-cloud/spring-cloud.html

**Comment by dsyer** [comment]
Fixed thanks (it was a typo). It's all here as well though: http://projects.spring.io/spring-cloud/spring-cloud.html

**Comment by Endron** [comment]
Thanks!
