### ISSUE TITLE
How to hide SSo client behind ZUUL proxy server?

### ISSUE THREAD

**Issue by chdanish** [spring-cloud/spring-cloud-security#70]
How to customize redirect URL with compromising security for example my current URI is as below :

Redirecting to 'http://localhost:8765/uaa/oauth/authorize?client_id=acme&redirect_uri=http://localhost:9999/sso/dashboard/login&response_type=code&state=5Qe5XL'  

And modified URI will be 

Redirecting to 'http://localhost:8765/uaa/oauth/authorize?client_id=acme&redirect_uri=http://localhost:8080/sso/dashboard/login&response_type=code&state=5Qe5XL'

where "http://localhost:8080" is my zuul proxy server.This way I can hide my client behind proxy gateway server

**Comment by dsyer** [comment]
You can register a fixed redirect URI in the auth server. That will work if you always redirect to the same place (you probably need to set`spring.oauth2.client.registeredRedirectUri` and `spring.oauth2.client.preEstablishedRedirectUri` on the server and client respectively, and `spring.oauth2.client.useCurrentUri=false` on the client). Beyond that you would need a change in the auth server itself (so in Spring Security OAuth).
