### ISSUE TITLE
OauthToken expiration being override to null in UserInfoTokenServices

### ISSUE THREAD

**Issue by seno5979** [spring-cloud/spring-cloud-security#71]
Hi,

accessToken expiration check is not working as expected on `Oauth2RestTemplate#getAccessToken()` when using `UserInfoTokenServices` as `ResourceServerTokenServices`.

The expiration info is being override by below code line :

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/UserInfoTokenServices.java#L120

**Comment by dsyer** [comment]
That code is in Spring Boot. Did you mean to open an issue there?
