### ISSUE TITLE
Support JWK Set responses in spring.oauth2.resource.jwt.keyUri

### ISSUE THREAD

**Issue by william-tran** [spring-cloud/spring-cloud-security#76]
This is a standard response defined by [RFC-7517](https://tools.ietf.org/html/rfc7517#section-5) and though UAA's /token_key endpoint doesn't emit its key in this format Google does: https://www.googleapis.com/oauth2/v3/certs. We should support the standard but keep existing behaviour for backwards compatibility.

**Comment by dsyer** [comment]
Isn't this a Spring Boot feature now? I assume that would be the best place to fix it.

**Comment by spencergibb** [comment]
@william-tran WDYT?

**Comment by william-tran** [comment]
Agreed, the work would be done here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java

**Comment by spencergibb** [comment]
Closing as the work needs to be done in boot.
