### ISSUE TITLE
Unable to get token scope in Principal from userInfoUri

### ISSUE THREAD

**Issue by sckoh** [spring-cloud/spring-cloud-security#78]
I'm using @EnableOAuth2Resource.
My userInfoUri controller return a Principal, when I log the Principal in the Authorization Server controller, it shows correct Authentication with scope details

    {  
       "details":{  
          "remoteAddress":"0:0:0:0:0:0:0:1",
          "sessionId":null,
          "tokenValue":"f5f3208e-5d7f-410d-b882-bf7ed404f3ae",
          "tokenType":"Bearer",
          "decodedDetails":{  
             "remoteAddress":"127.0.0.1",
             "sessionId":null,
             "tokenValue":"f5f3208e-5d7f-410d-b882-bf7ed404f3ae",
             "tokenType":"Bearer",
             "decodedDetails":null
          }
       },
       "authorities":[  

       ],
       "authenticated":true,
       "userAuthentication":{  
          "authenticated":true,
          "name":"soocheng",
          "principal":{  
             "@id":"1",
             "id":1,
             "nickname":"soocheng",
             "profilePicUrl":null,
             "userOAuths":[  
                {  
                   "@id":"2",
                   "id":2,
                   "oAuthProvider":"ifast",
                   "oAuthUid":"123456198101011234",
                   "accessToken":"ifasttoken123",
                   "refreshToken":null,
                   "createdDate":1442139317381,
                   "expireAt":null,
                   "user":{  
                      "@ref":"1"
                   },
                   "name":null,
                   "profilePicUrl":null
                }
             ],
             "rooms":null
          },
          "credentials":null,
          "authorities":[  

          ],
          "details":{  
             "user":{  
                "@ref":"1"
             },
             "password":null,
             "username":"soocheng",
             "authorities":[  

             ],
             "credentialsNonExpired":true,
             "accountNonLocked":true,
             "accountNonExpired":true,
             "enabled":true
          }
       },
       "oauth2Request":{  
          "clientId":"appclient",
          "scope":[  
             "read",
             "write"
          ],
          "requestParameters":{  
             "oauth_provider":"ifast",
             "grant_type":"password",
             "username":"123456198101011234"
          },
          "resourceIds":[  
             "social",
             "auth"
          ],
          "authorities":[  
             {  
                "authority":"ROLE_CLIENT"
             }
          ],
          "approved":true,
          "refresh":false,
          "redirectUri":null,
          "responseTypes":[  

          ],
          "extensions":{  

          },
          "grantType":"password",
          "refreshTokenRequest":null
       },
       "principal":{  
          "@ref":"1"
       },
       "credentials":"",
       "clientOnly":false,
       "name":"User [id=1, nickname=soocheng, userOAuths=[UserOAuth [id=2, oAuthProvider=ifast, oAuthUid=123456198101011234, accessToken=ifasttoken123, refreshToken=null, createdDate=2015-09-13 18:15:17.381, expireAt=null, user=soocheng, name=null, profilePicUrl=null]]]"
    }

However in my Resource Server, when I log the Principal in a controller, the scope details is gone,

```
org.springframework.security.oauth2.provider.OAuth2Authentication@38342c9: Principal: User [id=5, nickname=韩敏, userOAuths=[UserOAuth [id=6, oAuthProvider=ifast, oAuthUid=123456198101011234, accessToken=57d502f5-a383-4071-83d5-5d1dd3298840, refreshToken=null, createdDate=2015-09-14 14:55:36.108, expireAt=995753797, user=韩敏, name=null, profilePicUrl=null]]]; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=0:0:0:0:0:0:0:1, tokenType=BearertokenValue=<TOKEN>; Granted Authorities: ROLE_USER
```

Therefore, when I control a route with 

```
@PreAuthorize("#oauth2.hasScope('read')")
```

and i access it, it returns

    <oauth>
      <error_description>Insufficient scope for this resource</error_description>
      <error>insufficient_scope</error>
    </oauth>

**Comment by dsyer** [comment]
This feature is not being maintained here any more. It has moved to Spring Boot in version 1.3. Maybe open an issue there to track changes?
