### ISSUE TITLE
No @EnableOAuth2Resource in Spring Cloud Security 1.1?

### ISSUE THREAD

**Issue by sckoh** [spring-cloud/spring-cloud-security#81]
http://stackoverflow.com/questions/32709473/no-enableoauth2resource-in-spring-cloud-security-1-1-invalid-access-token-afte

After I update to 1.1, I just change the @EnableOAuth2Resource to @EnableResourceServer. However, it shows invalid access token when I call an protected api.

**Comment by marcosbarbero** [comment]
@EnableResourceServer did not the trick?

**Comment by sckoh** [comment]
no, I just revert back to spring cloud 1.0 and use back the @EnableOAuth2Resource

**Comment by dsyer** [comment]
You need to make some other changes (e.g. the config prefix changed from `spring.oauth2.*` to `security.oauth2.*`).

**Comment by spencergibb** [comment]
@sckoh did @dsyer's suggestion help?

**Comment by dsyer** [comment]
Check the blog as well: https://spring.io/blog/2015/11/30/migrating-oauth2-apps-from-spring-boot-1-2-to-1-3

**Comment by zeninpalm** [comment]
I ran into same issue! And I modified application.properties as suggested, just like this: "security.oauth2.resource.userInfoUri=http://localhost:9999/uaa/user", still not working!
