### ISSUE TITLE
How to get custom principal object in ResourceServer from AuthorizationServer

### ISSUE THREAD

**Issue by sckoh** [spring-cloud/spring-cloud-security#82]
http://stackoverflow.com/questions/32000501/how-to-custom-principle-object-with-spring-cloud-security#

I have the same situation as above Stackoverflow question.

I'm using @EnableOAuth2Resource and externalized the configuration(spring.oauth2.resourceuserInfoUri) in application.properties.

When I log the Principal obtained through Controller in authorization server, all my custom UserDetails information such as the userId, email, etc exists.
However, when I log the Principal obtained through Controller in my ResourceServer, the principal field only contain the username.

How can I can get the same whole UserDetails object from AuthorizationServer in ResourceServer?

**Comment by dsyer** [comment]
If you are using the `UserInfoTokenServices` you need to provide a user info endpoint with more details in it I guess, and then on the resource server you might need to unpack that into a custom `UserDetails` object by providing your own implementation of `UserInfoTokenServices`. The default implementation puts the whole content of the user endpoint in the authentication details of the user `Authentication` so you could also probably do it downstream of the token services.

**Comment by atif92** [comment]
Were you able to do this? I am stuck in similar problem

**Comment by odnanref** [comment]
Is this still valid when using PriincipalExtractor? 
[](https://stackoverflow.com/questions/45901014/spring-using-spel-principal?noredirect=1#comment78808088_45901014)

**Comment by dsyer** [comment]
`PrincipalExtractor` is a Spring Boot feature. It is part of a package of features that were moved from this project into Spring Boot almost 2 years ago. If you have questions about how to use it, StackOverflow is probably the best source.
