### ISSUE TITLE
Help with ADFS: cannot pass resource to Authorization Server in /authorize call

### ISSUE THREAD

**Issue by gouravsood** [spring-cloud/spring-cloud-security#83]
I am trying to setup integration with ADFS using sso sample  provided "https://github.com/spring-cloud-samples/sso". 

I have tested the ADFS integration using  /adfs/oauth2/authorize request with below params and presented with the Login Page from ADFS:

```
client_id=MyClientId
redirect_uri=http://XXXX:8080/Callback
response_type=code
resource=http://XXXX:8080
```

But when I am trying to use sso sample application, then its not passing resource param (all others are passed as required) which leads me to error page of ADFS.

Can you please confirm how resource param can be passed? Which property in application.yml will send this param?

**Comment by gouravsood** [comment]
Hi Team, any update on this please?

here resource refers to identifier associated with a Relying Party Trust. How I can configure a resource identifier to be sent to authorize call?

**Comment by gouravsood** [comment]
Hi team,

Any update on this please?

**Comment by dsyer** [comment]
What is ADFS? Maybe you could include a link to some docs. A sample project would be useful too.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
