### ISSUE TITLE
Default redirectUri for OAuth2

### ISSUE THREAD

**Issue by vajda** [spring-cloud/spring-cloud-security#86]
Hi, I'm using @EnableOAuth2Sso annotation on UI micro service, I configured in yml file:
security.oauth2:
  client:
    accessTokenUri: http://localhost:9090/authServer/oauth/token
    userAuthorizationUri: http://localhost:9090/authServer/oauth/authorize

But frontend keep adding url parameters, such as clientId (which I set in yml file also, so it is ok), response_type=code (which is also ok) and redirect_uri=http://localhost:8080/login  (which is NOT OK)
I'm wandering how can I set in yml configuration or at any other place default redirect url for my UI client? I changed userAuthorizationUri to include redirectUri and then I got two redirectUri-s in request to auth server. After login, I was redirected to the right address, but token was not acquired (I got 401 unauthorized), I assume that UI micro service is still using localhost:8080 as redirect uri when token is being acquired and that does not match other uri I placed in yml so server returns me 401.
So, how can I say to UI micro service which redirect Uri to use?

This is form auth server log:
[http-nio-9090-exec-6] INFO  o.s.s.o.p.endpoint.TokenEndpoint:178 - Handling error: RedirectMismatchException, Redirect URI mismatch.

**Comment by vajda** [comment]
I figured it out. It is
security.oauth2.client.preEstablishedRedirectUri
but it only works when security.oauth2.client.useCurrentUri is set to false

**Comment by anandkhotpccoe** [comment]
Same Error is coming.
@vajda  Even after setting the  security.oauth2.client.useCurrentUri to false. It is still redirecting me to the server.
