### ISSUE TITLE
#oauth2.hasScope and Resource Server

### ISSUE THREAD

**Issue by silent-box** [spring-cloud/spring-cloud-security#90]
Hello,

I have multiple Resource Servers that share an Authorization Server, and everything works pretty good.

Now I'm trying to protect Controllers in Resource Servers with `@PreAuthorize("#oauth2.hasScope('myscope')")` annotation, but it just rejects every call, even with the right scope.

Here is an example Resource Server code:

```java
@SpringBootApplication
@EnableResourceServer
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MyResourceApplication {

	public static void main(String[] args) {
		SpringApplication.run(StatisticsApplication.class, args);
	}
}
```
```java
@RestController
public class MyController {

	@PreAuthorize("#oauth2.hasScope('myscope')")
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String hello(Principal principal) {
		return "hello, " + principal.getName();
	}
}
```

I can see this in my logs:
```
Previously Authenticated: org.springframework.security.oauth2.provider.OAuth2Authentication@48cce0de: Principal: another-service; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=127.0.0.1, tokenType=BearertokenValue=<TOKEN>; Not granted any authorities
Voter: org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter@4cd3541a, returned: -1
Voter: org.springframework.security.access.vote.RoleVoter@7e09868e, returned: 0
Voter: org.springframework.security.access.vote.AuthenticatedVoter@23c38124, returned: 0
```

I guess there is some problem with Auth to Resource server communication, because the same Controller annotation works good in Auth server. And I can see with curl, that Auth server user-info-uri request returns serialized Principal object, which contains required scopes and other stuff.

How can i make my Resource server to work with #oauth2.hasScope properly?

Thank you.

**Comment by silent-box** [comment]
Also, during Resource server debugging, I can see that UsernamePasswordAuthenticationToken details contains incoming scope:

<img width="828" alt="screen shot 2016-02-03 at 23 27 08" src="https://cloud.githubusercontent.com/assets/12157601/12795984/c2033918-cacd-11e5-8578-74b2b0178e9e.png">

But my controller with `@PreAuthorize("#oauth2.hasScope('myscope')")` annotation still rejects any requests

**Comment by dsyer** [comment]
Can you move this question to Spring Boot please? We can fix it there because these features are no longer in Spring Cloud (as you can see from your example above which has no Cloud code in it).
