### ISSUE TITLE
Release 1.1.1 broken on Maven

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-security#98]
The released binary JARs on Maven for version 1.1.1 seem to be broken.
When I disassemble the classes contained in the JAR file, I see lines like `throw new Error("Unresolved compilation problems: ...` in every method and constructor.
Seems that the compilation broke during the release of the library.

**Comment by dsyer** [comment]
Hopefully 1.1.2 fixed it.
