### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by szantopeter** [spring-cloud/spring-cloud-security#99]
The documentation of spring cloud has a number of issues

- http://cloud.spring.io/spring-cloud-security/ : code snipplet does not compile
- http://cloud.spring.io/spring-cloud-security/spring-cloud-security.html
  - Github link in intro section points to invalid location : https://github.com/spring-cloud/spring-cloud-security/tree/master/src/main/asciidoc
  - Groovy examples only run if the spring_home environment variable is properly set. If not set then the full group name and version has to be added to the @Grab annotation. This is common mistake and might be noted
  -  Even after the groovy examples are running they don't behave as expected.
     - The first example with spring-boot-security does not ask for username, password, instead displays "authentication required"
     - The second example with spring-cloud-security redirects to localhost:8080/login and throws an exception "A redirect is required to get the users approval"
- The sso and authserver examples are working, but they are much more complex then described in the manual.

**Comment by szantopeter** [comment]
@dsyer

**Comment by dsyer** [comment]
Thanks for the heads up. That home page was just out of date (most of the features moved to Spring Boot in 1.3). Fixed in 26e9cbc.
